docker cp ./data/PARSED_alias.csv db:var/lib/mysql
docker cp ./data/PARSED_directions.csv db:var/lib/mysql
docker cp ./data/PARSED_ingredients.csv db:var/lib/mysql
docker cp ./data/PARSED_nutrition.csv db:var/lib/mysql
docker cp ./data/PARSED_recipes.csv db:var/lib/mysql
docker cp ./data/PARSED_recipe_ingredients.csv db:var/lib/mysql
docker cp ./data/PARSED_recipe_tags.csv db:var/lib/mysql
docker cp ./data/PARSED_users.csv db:var/lib/mysql
docker cp ./data/PARSED_reviews.csv db:var/lib/mysql
docker cp ./data/PARSED_tags.csv db:var/lib/mysql