version: "3"

services:
    mysqldb:
        image: mysql
        container_name: db
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql

    client-app:
        build:
            context: ./client-app
            dockerfile: Dockerfile
        depends_on:
            - mysqldb
        image: client-app
        restart: unless-stopped
        env_file: ./.env
        container_name: client-app
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_LOCAL_PORT
        ports:
            - "9229:9229"
            - "8080:8080"
        volumes:
            - ./client-app/build:/home/node/app/build
            - ./client-app/src:/home/node/app/src
            - ./client-app/nodemon.json:/home/node/app/nodemon.json
        stdin_open: true
        tty: true

    client-app-ui:
        build:
            context: ./client-app-ui
            dockerfile: Dockerfile
        depends_on:
            - client-app
        image: client-app-ui
        restart: unless-stopped
        container_name: client-app-ui
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        volumes:
            - ./client-app-ui/build:/home/node/app/build
            - ./client-app-ui/src:/home/node/app/src
        stdin_open: true
        tty: true

volumes:
    db: 
